import logging

from assignment.bakery.structures import (
    bakery_corner_narrow_to_narrow,
    bakery_corner_narrow_to_wide,
    bakery_corner_wide_to_narrow,
    bakery_corner_wide_to_wide,
    bakery_corridor_corner,
    bakery_corridor_end,
    bakery_corridor_entrance,
    bakery_corridor_straight,
    bakery_corridor_to_left,
    bakery_corridor_to_open,
    bakery_corridor_to_right,
    bakery_entrance_open,
    bakery_inner_corner_narrow,
    bakery_inner_corner_wide,
    bakery_middle_chairs,
    bakery_middle_counter,
    bakery_oven_narrow,
    bakery_oven_wide,
    bakery_wall_counter,
    bakery_wall_narrow,
    bakery_wall_wide,
    empty_space_air,
)
from assignment.utils.structure_adjacency import StructureAdjacency, all_rotations, check_symmetry
from assignment.utils.structure_rotation import StructureRotation

logger = logging.getLogger(__name__)

structure_adjecencies = {
    empty_space_air: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=empty_space_air,
        x_plus=[
            *all_rotations(empty_space_air),
            StructureRotation(bakery_corner_narrow_to_narrow, 1),
            StructureRotation(bakery_corner_narrow_to_narrow, 2),
            StructureRotation(bakery_corner_narrow_to_wide, 1),
            StructureRotation(bakery_corner_narrow_to_wide, 2),
            StructureRotation(bakery_corner_wide_to_narrow, 0),
            StructureRotation(bakery_corner_wide_to_narrow, 1),
            StructureRotation(bakery_corner_wide_to_wide, 0),
            StructureRotation(bakery_corner_wide_to_wide, 3),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_corner, 3),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_end, 1),
            StructureRotation(bakery_corridor_end, 2),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_entrance, 1),
            StructureRotation(bakery_corridor_entrance, 2),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 0),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_wall_wide, 2),
        ],
        x_minus=[
            *all_rotations(empty_space_air),
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_narrow_to_narrow, 3),
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_corner_narrow_to_wide, 3),
            StructureRotation(bakery_corner_wide_to_narrow, 2),
            StructureRotation(bakery_corner_wide_to_narrow, 3),
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_wide, 2),
            StructureRotation(bakery_corridor_corner, 0),
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_end, 2),
            StructureRotation(bakery_corridor_end, 3),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_entrance, 2),
            StructureRotation(bakery_corridor_entrance, 3),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 0),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_counter, 3),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
        z_plus=[
            *all_rotations(empty_space_air),
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_narrow_to_narrow, 1),
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_corner_narrow_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 0),
            StructureRotation(bakery_corner_wide_to_narrow, 3),
            StructureRotation(bakery_corner_wide_to_wide, 2),
            StructureRotation(bakery_corner_wide_to_wide, 3),
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_end, 1),
            StructureRotation(bakery_corridor_end, 3),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_entrance, 1),
            StructureRotation(bakery_corridor_entrance, 3),
            StructureRotation(bakery_corridor_straight, 1),
            StructureRotation(bakery_corridor_straight, 3),
            StructureRotation(bakery_corridor_to_left, 1),
            StructureRotation(bakery_corridor_to_right, 3),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
            StructureRotation(bakery_wall_wide, 1),
        ],
        z_minus=[
            *all_rotations(empty_space_air),
            StructureRotation(bakery_corner_narrow_to_narrow, 2),
            StructureRotation(bakery_corner_narrow_to_narrow, 3),
            StructureRotation(bakery_corner_narrow_to_wide, 2),
            StructureRotation(bakery_corner_narrow_to_wide, 3),
            StructureRotation(bakery_corner_wide_to_narrow, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 2),
            StructureRotation(bakery_corner_wide_to_wide, 0),
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corridor_corner, 0),
            StructureRotation(bakery_corridor_corner, 3),
            StructureRotation(bakery_corridor_end, 1),
            StructureRotation(bakery_corridor_end, 2),
            StructureRotation(bakery_corridor_end, 3),
            StructureRotation(bakery_corridor_entrance, 1),
            StructureRotation(bakery_corridor_entrance, 2),
            StructureRotation(bakery_corridor_entrance, 3),
            StructureRotation(bakery_corridor_straight, 1),
            StructureRotation(bakery_corridor_straight, 3),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_right, 1),
            StructureRotation(bakery_entrance_open, 2),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_counter, 2),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_wall_wide, 3),
        ],
    ),
    bakery_corner_narrow_to_narrow: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corner_narrow_to_narrow,
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 3),
            StructureRotation(bakery_corner_narrow_to_wide, 3),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_counter, 3),
            StructureRotation(bakery_wall_narrow, 0),
        ],
    ),
    bakery_corner_narrow_to_wide: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corner_narrow_to_wide,
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
        ],
        z_minus=[
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
    ),
    bakery_corner_wide_to_narrow: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corner_wide_to_narrow,
        x_plus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_wide, 2),
            StructureRotation(bakery_corner_wide_to_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            StructureRotation(bakery_corridor_to_right, 1),
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
        ],
    ),
    bakery_corner_wide_to_wide: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corner_wide_to_wide,
        x_plus=[
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corner_narrow_to_wide, 3),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
        ],
        z_plus=[
            StructureRotation(bakery_corner_wide_to_wide, 3),
            StructureRotation(bakery_corner_wide_to_narrow, 0),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 1),
            StructureRotation(bakery_corridor_to_open, 0),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
        ],
    ),
    bakery_corridor_corner: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_corner,
        x_minus=[
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_corner, 3),
            StructureRotation(bakery_corridor_end, 1),
            StructureRotation(bakery_corridor_entrance, 1),
            StructureRotation(bakery_corridor_straight, 1),
            StructureRotation(bakery_corridor_straight, 3),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_right, 3),
            StructureRotation(bakery_corridor_to_open, 3),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_corridor_to_open, 2),
        ],
    ),
    bakery_corridor_end: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_end,
        z_minus=[
            StructureRotation(bakery_corridor_corner, 0),
            StructureRotation(bakery_corridor_corner, 3),
            StructureRotation(bakery_corridor_entrance, 2),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 0),
            StructureRotation(bakery_corridor_to_right, 0),
            StructureRotation(bakery_corridor_to_open, 0),
        ],
    ),
    bakery_corridor_entrance: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_entrance,
        z_minus=[
            StructureRotation(bakery_corridor_corner, 0),
            StructureRotation(bakery_corridor_corner, 3),
            StructureRotation(bakery_corridor_end, 2),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 0),
            StructureRotation(bakery_corridor_to_right, 0),
            StructureRotation(bakery_corridor_to_open, 0),
        ],
    ),
    bakery_corridor_straight: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_straight,
        z_plus=[
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_corridor_to_open, 2),
        ],
        z_minus=[
            StructureRotation(bakery_corridor_corner, 0),
            StructureRotation(bakery_corridor_corner, 3),
            StructureRotation(bakery_corridor_end, 2),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 0),
            StructureRotation(bakery_corridor_to_right, 0),
            StructureRotation(bakery_corridor_to_open, 0),
        ],
    ),
    bakery_corridor_to_left: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_to_left,
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_wide, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_corridor_to_open, 2),
        ],
        z_minus=[
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
    ),
    bakery_corridor_to_open: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_to_open,
        x_plus=[
            StructureRotation(bakery_corner_wide_to_narrow, 3),
            StructureRotation(bakery_corner_wide_to_wide, 2),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
        ],
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_wide, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_corridor_to_open, 2),
        ],
        z_minus=[
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_entrance_open, 2),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 1),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
            StructureRotation(bakery_wall_counter, 2),
        ],
    ),
    bakery_corridor_to_right: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_corridor_to_right,
        x_plus=[
            StructureRotation(bakery_corner_wide_to_narrow, 3),
            StructureRotation(bakery_corner_wide_to_wide, 2),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_corner, 1),
            StructureRotation(bakery_corridor_corner, 2),
            StructureRotation(bakery_corridor_end, 0),
            StructureRotation(bakery_corridor_entrance, 0),
            StructureRotation(bakery_corridor_straight, 0),
            StructureRotation(bakery_corridor_straight, 2),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_right, 2),
            StructureRotation(bakery_corridor_to_open, 2),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_wide, 2),
            StructureRotation(bakery_corner_wide_to_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            StructureRotation(bakery_corridor_to_right, 1),
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
        ],
    ),
    bakery_entrance_open: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_entrance_open,
        x_plus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
        ],
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_wide, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
        ],
        z_minus=[
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_entrance_open, 2),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 1),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
            StructureRotation(bakery_wall_counter, 2),
        ],
    ),
    bakery_inner_corner_wide: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_inner_corner_wide,
        x_plus=[
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 1),
            StructureRotation(bakery_inner_corner_wide, 2),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
            StructureRotation(bakery_wall_counter, 3),
        ],
        x_minus=[
            StructureRotation(bakery_corner_wide_to_narrow, 1),
            StructureRotation(bakery_corner_wide_to_wide, 0),
            StructureRotation(bakery_corridor_to_left, 2),
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
            StructureRotation(bakery_entrance_open, 2),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_to_open, 0),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_narrow, 1),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
            StructureRotation(bakery_wall_counter, 0),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_wide, 2),
            StructureRotation(bakery_corner_wide_to_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            StructureRotation(bakery_corridor_to_right, 1),
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
        ],
    ),
    bakery_inner_corner_narrow: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_inner_corner_narrow,
        x_plus=[
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 1),
            StructureRotation(bakery_inner_corner_wide, 2),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
            StructureRotation(bakery_wall_counter, 3),
        ],
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 2),
            StructureRotation(bakery_corner_narrow_to_wide, 2),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_wall_counter, 2),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_to_open, 0),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_narrow, 1),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
            StructureRotation(bakery_wall_counter, 0),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 2),
            StructureRotation(bakery_corner_wide_to_narrow, 1),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
    ),
    bakery_middle_chairs: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_middle_chairs,
        x_plus=[
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 1),
            StructureRotation(bakery_inner_corner_wide, 2),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
            StructureRotation(bakery_wall_counter, 3),
        ],
        x_minus=[
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_to_open, 0),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_narrow, 1),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
            StructureRotation(bakery_wall_counter, 0),
        ],
        z_minus=[
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_entrance_open, 2),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 1),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
            StructureRotation(bakery_wall_counter, 2),
        ],
    ),
    bakery_middle_counter: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_middle_counter,
        x_plus=[
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 1),
            StructureRotation(bakery_inner_corner_wide, 2),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
            StructureRotation(bakery_wall_counter, 3),
        ],
        x_minus=[
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corridor_to_open, 0),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_narrow, 1),
            StructureRotation(bakery_oven_wide, 1),
            StructureRotation(bakery_wall_wide, 1),
            StructureRotation(bakery_wall_counter, 0),
        ],
        z_minus=[
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_entrance_open, 2),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 1),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
            StructureRotation(bakery_wall_counter, 2),
        ],
    ),
    bakery_oven_narrow: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_oven_narrow,
        x_minus=[
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_wide_to_narrow, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_wall_counter, 3),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 3),
            StructureRotation(bakery_corner_narrow_to_wide, 3),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_counter, 3),
            StructureRotation(bakery_wall_narrow, 0),
        ],
    ),
    bakery_oven_wide: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_oven_wide,
        x_minus=[
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_corner_wide_to_wide, 2),
            StructureRotation(bakery_corridor_to_left, 0),
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_corridor_to_right, 3),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
        z_minus=[
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
    ),
    bakery_wall_counter: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_wall_counter,
        x_plus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
        ],
        x_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_entrance_open, 0),
            StructureRotation(bakery_oven_narrow, 1),
            StructureRotation(bakery_wall_counter, 0),
            StructureRotation(bakery_wall_narrow, 1),
        ],
        z_minus=[
            StructureRotation(bakery_corridor_to_open, 2),
            StructureRotation(bakery_entrance_open, 2),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 1),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 1),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 3),
            StructureRotation(bakery_wall_narrow, 3),
            StructureRotation(bakery_oven_wide, 3),
            StructureRotation(bakery_wall_wide, 3),
            StructureRotation(bakery_wall_counter, 2),
        ],
    ),
    bakery_wall_narrow: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_wall_narrow,
        x_minus=[
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 0),
            StructureRotation(bakery_corner_wide_to_narrow, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_narrow, 0),
            StructureRotation(bakery_wall_counter, 3),
        ],
        z_minus=[
            StructureRotation(bakery_corner_narrow_to_narrow, 3),
            StructureRotation(bakery_corner_narrow_to_wide, 3),
            StructureRotation(bakery_inner_corner_narrow, 2),
            StructureRotation(bakery_oven_narrow, 0),
            StructureRotation(bakery_wall_counter, 3),
            StructureRotation(bakery_wall_narrow, 0),
        ],
    ),
    bakery_wall_wide: StructureAdjacency(
        empty_space_air=empty_space_air,
        structure_name=bakery_wall_wide,
        x_minus=[
            StructureRotation(bakery_corridor_to_open, 1),
            StructureRotation(bakery_entrance_open, 1),
            StructureRotation(bakery_inner_corner_narrow, 0),
            StructureRotation(bakery_inner_corner_narrow, 3),
            StructureRotation(bakery_inner_corner_wide, 0),
            StructureRotation(bakery_inner_corner_wide, 3),
            *all_rotations(bakery_middle_chairs),
            *all_rotations(bakery_middle_counter),
            StructureRotation(bakery_oven_narrow, 2),
            StructureRotation(bakery_wall_narrow, 2),
            StructureRotation(bakery_oven_wide, 2),
            StructureRotation(bakery_wall_wide, 2),
            StructureRotation(bakery_wall_counter, 1),
        ],
        z_plus=[
            StructureRotation(bakery_corner_narrow_to_wide, 0),
            StructureRotation(bakery_corner_wide_to_wide, 2),
            StructureRotation(bakery_corridor_to_left, 0),
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_corridor_to_right, 3),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
        z_minus=[
            StructureRotation(bakery_corner_wide_to_wide, 1),
            StructureRotation(bakery_corner_wide_to_narrow, 2),
            StructureRotation(bakery_inner_corner_wide, 2),
            StructureRotation(bakery_corridor_to_left, 3),
            StructureRotation(bakery_corridor_to_open, 3),
            StructureRotation(bakery_entrance_open, 3),
            StructureRotation(bakery_oven_wide, 0),
            StructureRotation(bakery_wall_wide, 0),
        ],
    ),
}

if __name__ == "__main__":
    print(structure_adjecencies[bakery_corner_wide_to_narrow].adjecent_structrues("z_minus", 3))

    check_symmetry(structure_adjecencies)
